ROSE: Rose::CodeGen::Factory< CRT, API > Class Template Reference
Rose::CodeGen::Factory< CRT, API > Class Template Reference
Description
template<typename CRT, typename API>
class Rose::CodeGen::Factory< CRT, API >
constructs expressions and types for the given API
Template Parameters
CRT https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern
API a specialization of Rose::CodeGen::API
Definition at line 18 of file Factory.h.
#include <Rose/CodeGen/Factory.h>
Public Types
using factory_t = Factory< CRT, API >
Public Member Functions
Factory (Driver &driver_)
template<Object otag, typename... Args>
declaration_t< otag > * instantiate (symbol_t< otag > *API::*obj, SgNamedType *parent, Args... args)
Return an instantiation.
template<Object otag, typename... Args>
reference_t< otag > * reference (symbol_t< otag > *API::*obj, SgNamedType *parent, Args... args)
Return an expression or type referencing the object.
template<Object otag, typename... Args>
SgExpression * access (symbol_t< otag > *API::*obj, SgExpression *parent, Args... args)
Build expression to access a member of the parent expression.
template<Object otag, typename... Args>
access_return_t< otag > * access (symbol_t< otag > *API::*obj, SgNamedType *parent, Args... args)
Build expression or type to access static member and subtype of the parent type.
Public Attributes
Driver & driver
API api
Protected Types
template<Object otag>
using access_return_t = std::conditional_t< otag==Object::a_class||otag==Object::a_typedef, SgType, SgExpression >
Select return type for access based on Object type.
Member Typedef Documentation
access_return_t
template<typename CRT , typename API > template<Object otag> using Rose::CodeGen::Factory< CRT, API >::access_return_t = std::conditional_t<otag == Object::a_class || otag == Object::a_typedef, SgType, SgExpression> protected
Select return type for access based on Object type.
Template Parameters
otag must be one of a_class/a_typedef or a_variable/a_function
Definition at line 141 of file Factory.h.
Member Function Documentation
instantiate()
template<typename CRT , typename API > template<Object otag, typename... Args> declaration_t<otag>* Rose::CodeGen::Factory< CRT, API >::instantiate (symbol_t< otag > *API::* obj, SgNamedType * parent, Args... args) inline
Return an instantiation.
Template Parameters
otag must be one of a_class/a_typedef/a_variable/a_function
Args types of the nodes to use as template arguments (SgType/SgExpression for type/non-type respectively
Parameters
obj must points to a template symbol
args nodes to use as template arguments
parent is used when called by reference which was called by one of the access methods
Returns
a template instantiation
Definition at line 59 of file Factory.h.
reference()
template<typename CRT , typename API > template<Object otag, typename... Args> reference_t<otag>* Rose::CodeGen::Factory< CRT, API >::reference (symbol_t< otag > *API::* obj, SgNamedType * parent, Args... args) inline
Return an expression or type referencing the object.
Args are forwarded to instantiate as needed.
Template Parameters
otag must be one of a_class/a_typedef/a_variable/a_function
Args types of template arguments (see instantiate)
Parameters
obj points to a symbol
args template arguments (see instantiate)
parent is used when called by one of the access methods
Returns
a reference expression
Definition at line 80 of file Factory.h.
Referenced by Rose::CodeGen::Factory< CRT, API >::access().
access() [1/2]
template<typename CRT , typename API > template<Object otag, typename... Args> SgExpression* Rose::CodeGen::Factory< CRT, API >::access (symbol_t< otag > *API::* obj, SgExpression * parent, Args... args) inline
Build expression to access a member of the parent expression.
Args are forwarded to instantiate as needed.
Template Parameters
otag must be one of a_variable/a_function
Args types of template arguments (see instantiate)
Parameters
obj points to a symbol
parent
args template arguments (see instantiate)
Returns
either . or -> operator with parent as lhs and reference(obj, args...) as rhs
Definition at line 110 of file Factory.h.
References SageBuilder::buildArrowExp(), SageBuilder::buildDotExp(), SgExpression::get_type(), and Rose::CodeGen::Factory< CRT, API >::reference().
access() [2/2]
template<typename CRT , typename API > template<Object otag, typename... Args> access_return_t<otag>* Rose::CodeGen::Factory< CRT, API >::access (symbol_t< otag > *API::* obj, SgNamedType * parent, Args... args) inline
Build expression or type to access static member and subtype of the parent type.
Args are forwarded to instantiate as needed.
Template Parameters
otag must be one of a_class/a_typedef or a_variable/a_function
Args types of template arguments (see instantiate)
Parameters
obj points to a symbol
lhs
args template arguments (see instantiate)
Definition at line 157 of file Factory.h.
References Rose::CodeGen::Factory< CRT, API >::reference().
The documentation for this class was generated from the following file:
Factory.h