ROSE: Sawyer::CommandLine::UserAction< Functor > Class Template Reference
Sawyer::CommandLine::UserAction< Functor > Class Template Reference
Description
template<class Functor>
class Sawyer::CommandLine::UserAction< Functor >
Wrapper around a user functor.
User code doesn't often use reference counting smart pointers for functors, but more often creates functors in global data or on the stack. The purpose of UserAction is to be a wrapper around these functors, to be a bridge between the world of reference counting pointers and objects or object references. For example, say the user has a function like this:
void showRawManPage(const ParserResult *cmdline) {
    std::cout <<cmdline->parser()->manpage();
    exit(0);
}
Then the functor/function can be used like this:
switchGroup.insert(Switch("raw-man")
                   .action(userAction(showRawManPage))
                   .doc("Prints the raw nroff man page to standard output."));
Definition at line 1812 of file util/Sawyer/CommandLine.h.
#include <CommandLine.h>
Public Types
typedef SharedPointer< class UserAction > Ptr
Reference counting pointer for this class.
Public Types inherited from Sawyer::CommandLine::SwitchAction
typedef SharedPointer< SwitchAction > Ptr
Reference counting pointer for this class.
Static Public Member Functions
static Ptr instance (Functor &f)
Allocating constructor.
Protected Member Functions
UserAction (Functor &f)
Constructor for derived classes.
virtual void operator() (const ParserResult &parserResult)
Additional Inherited Members
Public Member Functions inherited from Sawyer::CommandLine::SwitchAction
void run (const ParserResult &parserResult)
Runs the action.
Public Member Functions inherited from Sawyer::SharedObject
SharedObject ()
Default constructor.
SharedObject (const SharedObject &)
Copy constructor.
virtual ~SharedObject ()
Virtual destructor.
SharedObject & operator= (const SharedObject &)
Assignment.
Constructor & Destructor Documentation
UserAction()
template<class Functor > Sawyer::CommandLine::UserAction< Functor >::UserAction (Functor & f) inline protected
Constructor for derived classes.
Non-subclass users should use instance instead.
Definition at line 1816 of file util/Sawyer/CommandLine.h.
Referenced by Sawyer::CommandLine::UserAction< Functor >::instance().
Member Function Documentation
instance()
template<class Functor > static Ptr Sawyer::CommandLine::UserAction< Functor >::instance (Functor & f) inline static
Allocating constructor.
Returns a pointer to a new UserAction object. Uses will most likely want to use the userAction factory instead, which requires less typing.
See also
Command line action factories, and the SwitchAction class.
Definition at line 1825 of file util/Sawyer/CommandLine.h.
References Sawyer::CommandLine::UserAction< Functor >::UserAction().
Referenced by Sawyer::CommandLine::userAction().
The documentation for this class was generated from the following file:
util/Sawyer/CommandLine.h