ROSE: ssa_private::DataflowCfgFilter Struct Reference
ssa_private::DataflowCfgFilter Struct Reference
Description
Filter which determines which CFG nodes appear in the CFg used to propagate reaching definitions.
Getting this right is very important. If an AST node appears twice in the filtered CFG, reaching definitions will be propagated to it from two distinct locations. So, each AST node must appear at most once, (with the exception of SgFunctionDefinition)
Definition at line 14 of file dataflowCfgFilter.h.
#include <dataflowCfgFilter.h>
Public Member Functions
bool operator() (CFGNode cfgn) const
Determines if the provided CFG node should be traversed during DefUse.
Member Function Documentation
operator()()
bool ssa_private::DataflowCfgFilter::operator() (CFGNode cfgn) const inline
Determines if the provided CFG node should be traversed during DefUse.
Parameters
cfgn The node in question.
Returns
Whether it should be traversed.
Definition at line 22 of file dataflowCfgFilter.h.
References SgNode::cfgForBeginning(), SgNode::cfgForEnd(), and SgNode::variantT().
The documentation for this struct was generated from the following file:
dataflowCfgFilter.h