include $(top_srcdir)/config/Makefile.for.ROSE.includes.and.libs

# programTransformation

SUBDIRS = \
        astDiagnostics \
        astProcessing \
        astQuery \
        astUtil \
        programAnalysis \
        programTransformation

EXTRA_DIST = CMakeLists.txt
