name: Auto Testing

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        gnu: [9]

    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/bin/gcc-${{ matrix.gnu }}
      CXX: /usr/bin/g++-${{ matrix.gnu }}
      LD_LIBRARY_PATH: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server:/usr/lib/x86_64-linux-gnu

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git -c "http.extraheader=Authorization: basic ${{ secrets.SUBMODULE_TOKEN }}" -c protocol.version=2 submodule update --init --force --recursive --depth=1
        git submodule status

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk && \
        sudo apt-get install -y \
          antlr4 \
          automake \
          autotools-dev \
          bison \
          build-essential \
          cmake \
          curl \
          flex \
          g++-${{ matrix.gnu }} \
          gdb \
          gfortran-${{ matrix.gnu }} \
          ghostscript \
          git \
          graphviz \
          libantlr4-runtime-dev \
          libboost-all-dev \
          libtool \
          python3-dev

    - name: Configure
      run: |
        cd $GITHUB_WORKSPACE
        ./build
        mkdir ../rex_build
        cd ../rex_build
        $GITHUB_WORKSPACE/configure --prefix=$GITHUB_WORKSPACE/../rex_install --with-boost=/usr --with-boost-libdir=/usr/lib/x86_64-linux-gnu --enable-languages=c,c++,fortran --disable-tests-directory --disable-tutorial-directory

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/../rex_build
        make core -j2
        make install-core -j2

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/../rex_build
        make check-core -j2
        cd $GITHUB_WORKSPACE/../rex_build/tests/nonsmoke/functional/CompileTests/OpenMP_tests
        make check -j2
        cd $GITHUB_WORKSPACE/../rex_build/tests/nonsmoke/functional/roseTests/astInterfaceTests
        make check -j2
